source 'https://rubygems.org'

gem 'csv'
gem 'rake'
gem 'jekyll', '~> 4.4'
gem 'jekyll-paginate', '~> 1.1'
gem 'jekyll-redirect-from', '~> 0.17.0'
gem 'jekyll-sass-converter', '~> 2.2'
gem 'jekyll-sitemap', '~> 1.4'
gem 'html-proofer'
gem 'webrick'
gem 'typhoeus'
gem 'ruby-link-checker'
gem 'jekyll-md', '~> 0.2.0'
