name: Check Style
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v46.0.4
        id: changed_files
        with:
          files: |
            **/**.md
            **/**.markdown
            !_styles/**/*.md
      - uses: errata-ai/vale-action@v2.1.1
        if: steps.changed_files.outputs.all_changed_files != ''
        with:
          version: 3.7.1
          reporter: github-check
          files: ${{ steps.changed_files.outputs.all_changed_files }}
